[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.metadata]
allow-direct-references = true

[project]
name = "test_drscook"
version = "0.1.0"
description = "A Demo for my stackoverflow question"
dependencies = [
    "codetiming",
    #"helpers_drscook",
    "git+https://github.com/drscook/helpers_drscook",
    #"my_local_package @ {root:uri}/my_local_package",
]
