[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"


[project]
name = "test_drscook"
authors = [
    {name = "Thomas Kluyver", email = "thomas@kluyver.me.uk"},
]
readme = "README.md"
classifiers = [
    "License :: OSI Approved :: MIT License",
]
requires-python = ">=3.8"
dependencies = ["codetiming"]
dynamic = ["version", "description"]
