[build-system]
requires      = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "test"
authors = [
    { name = "Geir Arne Hjelle", email = "geirarne@gmail.com" },
]
readme = "README.md"
dynamic = ["version", "description"]
classifiers = [
    "Programming Language :: Python",
    "Topic :: Education",
]
requires-python = ">=3.8"
dependencies = ['codetiming']
